### ISSUE TITLE
Does this library also covers contrast and Dynamic text font sizes are unsupported related a11y issues?

### ISSUE THREAD

**Issue by mohsinbmwm3** [rwapp/A11yUITests#18]
1. Contrast nearly passed 
2. Contrast failed 
3. Potentially inaccessible text 
4. Dynamic text font sizes are unsupported 
5. Dynamic text font sizes are partially unsupported

**Comment by rwapp** [comment]
Unfortunately it's not possible to detect these with XCUITests.

The purpose of this project is to add common accessibility checks into an existing XCUITest suite, so adding these would be outside the scope of this project.

If it does become possible to detect these, I'd love to add these checks.
