### ISSUE TITLE
CGFloat not being recognized

### ISSUE THREAD

**Issue by daemedeor** [rwapp/A11yUITests#30]
Having a bit of importing this to my project. The compiler is complaining that CGFloat is not being imported from Foundation. I'm running iOS 11-14 on Xcode 12.4 When I changed the foundation reference to the top to CoreGraphics, it was recognized. As far as I can tell, you're mostly using foundation to reference CGFloat (no idea why it does not exist anymore) but it builds fine with replacing that one reference. Would you be opposed to a PR to change it to CoreGraphics?

**Comment by rwapp** [comment]
Interesting, I wonder why this would have changed. 🤔 
I am able to replicate this too. CoreGraphics appears to be imported by Foundation, so I don't understand why it wouldn't be able to find a definition for CFGloat.
Without any clearer indication why this is happening, I'd be happy to get a PR to update this import, thank you 🙂
